### PR TITLE
JENKINS-66319 Forward compatibility with upcoming guava version

### PR DESCRIPTION
**Pull request by timja**
See https://issues.jenkins.io/browse/JENKINS-66319

cc @viglesiasce

### CODE REVIEW

**Comment by basil** [comment]
@viglesiasce Would it be possible to take a look at this PR?

**Comment by basil** [comment]
@viglesiasce Gentle ping. It would be nice to get this PR merged and released to facilitate [the Guava upgrade in Jenkins core](https://www.jenkins.io/blog/2021/11/09/guava-upgrade/).

**Comment by basil** [comment]
@viglesiasce Gentle ping. It would be nice to get this PR merged and released to facilitate [the Guava upgrade in Jenkins core](https://www.jenkins.io/blog/2021/11/09/guava-upgrade/).

**Comment by viglesiasce** [comment]
@basil any pointers on how to solve the test issues?

**Comment by basil** [comment]
I suggest reading the [Improve a Plugin Tutorial ](https://www.jenkins.io/doc/developer/tutorial-improve/).

**Comment by viglesiasce** [comment]
Thanks!

**Pull request merged**
